mod

diff --git a/sh/login b/sh/login
--- a/sh/login
+++ b/sh/login
@@ -14,7 +14,7 @@ pass=`$COMMON_PATH/getParam premium auth_pass`
 ##############################################
 
 ####################################
-# Logout Function
+# Login
 ####################################
 wget -q -T $HTTP_TIMEOUT -U "$USER_AGENT" \
 	--post-data="mail=$mail&pass=$pass" \
@@ -24,8 +24,8 @@ wget -q -T $HTTP_TIMEOUT -U "$USER_AGENT" \
 	$url/login/login
 
 if [ ! -f $COOKIE_FILE ]; then
-	echo "failed login.:[$mail]"
-	exit 1
+	echo -n "failed login.:[$mail]"
+	exit 1;
 fi
 
 ####################################
@@ -38,17 +38,18 @@ wget -q -T $HTTP_TIMEOUT -U "$USER_AGENT" \
 	$url/webapi/member/login/check
 
 if [ $? -ne 0 ]; then
-	echo "failed login.:[$mail]"
+	echo -n "failed login.:[$mail]"
 	rm -rf $checkfile
-	exit 1
+	exit 1;
 fi
 
 ####################################
 # paid member
 ####################################
 JSON=`perl -ne 'print $1 if(/\{(.*)\}/i)' $checkfile`
-echo `common/checkPaidMember $JSON`".:[$mail]"
+echo -n `common/checkPaidMember $JSON`".:[$mail]"
 ret=$?
 isPremium=$ret
 rm -rf $checkfile
+exit $isPremium
 
